---
language: go

go:
  - 1.12.x
  - 1.11.x
  - 1.x

env:
  global:
    - GO111MODULE=on
  matrix:
    - GOOS=linux GOARCH=386
    - GOOS=linux GOARCH=amd64
    - GOOS=linux GOARCH=arm
    - GOOS=linux GOARCH=arm64
    - GOOS=freebsd GOARCH=386
    - GOOS=freebsd GOARCH=amd64
    - GOOS=freebsd GOARCH=arm
    - GOOS=freebsd GOARCH=arm64

cache:
  directories:
    - vendor

before_cache:
  - go mod tidy

script:
  - go mod vendor
  - go build -mod vendor .
